name: First_workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello
        run: |
          echo hey there
          date
          echo good morning
      
  
